### ISSUE TITLE
Is it possible to store files in different folders(profile images/article files)

### ISSUE THREAD

**Issue by Misavan** [trntv/yii2-file-kit#114]
I wont to separeate files depend on section/item type. As example to have diffent folders for: profile images; news attachments; products files. Is it possible without configuring new component in config setion, per each section/item type ?

**Comment by fbalabanov** [comment]
for uploading to different folder, I have made an widget based on yii2-file-kit

**Comment by fbalabanov** [comment]
I have made own repo.
https://github.com/fbalabanov/yii2-file-kit.git

**Comment by Misavan** [comment]
@fbalabanov Thankyou. I will try it.

**Comment by cncap** [comment]
@fbalabanov If you merge it into the main branch of trntv, God will praise your contribution 👍

**Comment by fbalabanov** [comment]
Thank you.
it was fixed at your end?

**Comment by cncap** [comment]
Not yet, because I may need it in the future, it is not necessary at the moment, so it is temporarily shelved and look forward to your merger~
