### ISSUE TITLE
To many empty inputs in POST

### ISSUE THREAD

**Issue by empk** [trntv/yii2-file-kit#16]
Used in profile in yii2-starter-kit as widget.

$form->field($model, 'picture')->widget(\trntv\filekit\widget\SingleFileUpload::classname(), [
        'url' => ['avatar-upload', 'category' => 'avatar']
])

Sends UserProfile[picture] param three times.

POST params:
UserProfile[picture]	http://storage.aqstarter.local/1/OkJfV6z79Na3tTQ8Fk88BMoJgMc6NqOS.png
UserProfile[picture]	
UserProfile[picture]

**Comment by trntv** [comment]
What version of file kit is in your starter-kit ``composer.json``? ``~0.3``? If so, change it to ``*`` or ``dev-master``. this looks ugly but it is temporary.

**Comment by empk** [comment]
After changing version from `~0.3` to `*` upload works fine.
