### ISSUE TITLE
upload file permissions

### ISSUE THREAD

**Issue by cgfix** [trntv/yii2-file-kit#19]
Hi,
sorry to bother you, but I had simple question about this file kit. I installed the yii starter kit that has this and when I upload a file the permissions are set to 600. The starter kit also has the file manager with it and it does not have this issue. So is there a place to set the upload permissions or is this dependent on my server somehow? What could be causing this?

Thanks

**Comment by trntv** [comment]
Hi, 600 is a default permissions for uploaded files. You don't need to fix it, you need to properly configure your webserver to work with these files.
