### ISSUE TITLE
vaildationRules and  acceptFileType

### ISSUE THREAD

**Issue by fkhateeb** [trntv/yii2-file-kit#23]
Hi,
on the file **\vendor\trntv\yii2-file-kit\src\widget\Upload.php**

I see there attribute for specifying  types needed , how can I use this I tried some regular expressions and file types and nothing succeeded .
Also,  on **\vendor\trntv\yii2-file-kit\src\actions\UploadAction.php**
there array for validationRules how I can use it ..
thank you a lot  for  your contributions in building such kits.
best regards,
Fady

**Comment by trntv** [comment]
Hi.
For widget - https://github.com/blueimp/jQuery-File-Upload/wiki/Options#validation-options
For action - https://github.com/yiisoft/yii2/blob/master/docs/guide/input-validation.md#ad-hoc-validation- (validation is performed via DynamicModel)

**Comment by fkhateeb** [comment]
thank you for reply.. i have tried this 
# <?= $form->field($model, 'picture')->widget(\trntv\filekit\widget\Upload::classname(), [
        'url'=>['avatar-upload'],
        'acceptFileTypes'=>'/(\.|\/)(gif|jpe?g|png)$/i',
    
    ]) ?> #
but still uploading other file types

**Comment by trntv** [comment]
update your code to 1.0.1
