### ISSUE TITLE
Files rights

### ISSUE THREAD

**Issue by Vaom** [trntv/yii2-file-kit#36]
How to change the files rights.

**Comment by Vaom** [comment]
public function actions(){
        return [
            'avatar-upload'=>[
                'class'=>UploadAction::className(),
                'fileProcessing'=>function($file){
                        // change the files rights
                        chmod($file->path->getPath(), 0755);
                }
            ]
        ];
    }

**Comment by trntv** [comment]
:-)
but you shouldn't change file rights for security reasons
