### ISSUE TITLE
Не работает в kartik-grid

### ISSUE THREAD

**Issue by zvinger** [trntv/yii2-file-kit#40]
Не работает виджет при вызове формы в модальном окне (как это устроено в kartik-grid). input file работает как обычный загрузчик файлов в html без удобного интерфейса. В то же время, если попасть на форму без ajax то все работает отлично.

**Comment by trntv** [comment]
Ну это довольно стандартная ситуация. Понятия не имею как у в kartik-grid работает ajax, но если через renderAjax, то таких проблем быть не должно.
