### ISSUE TITLE
Редирект после загрузки

### ISSUE THREAD

**Issue by Rinat-wc** [trntv/yii2-file-kit#47]
Каким образом можно корректно сделать редирект на определенный action после загрузки файла на странице вывода виджета. Т.е можно ли передать и как параметр для редиректа аналогично указанию размера файла или его расширения (maxFileSize, acceptFileTypes)?

**Comment by trntv** [comment]
ну вообще никак, виджет загрузки не подразумевает редирект. Если в обозримом будущем найду немного времени, добавлю возможность назначать обработчики событий.
