### ISSUE TITLE
Messages error

### ISSUE THREAD

**Issue by XzAeRo** [trntv/yii2-file-kit#51]
```
The message file for category 'app' does not exist: /usr/share/nginx/application/common/messages/es-CL/app.php Fallback file does not exist as well: /usr/share/nginx/application/common/messages/es/app.php
/usr/share/nginx/application/vendor/trntv/yii2-file-kit/src/widget/Upload.php (97)
/usr/share/nginx/application/backend/views/some-view/_form.php (48)
/usr/share/nginx/application/backend/views/some-view/update.php (19)
```
 The problem is in [this lines](https://github.com/trntv/yii2-file-kit/blob/master/src/widget/Upload.php#L96-L101), because, at least in my application, the `app` messages category doesn't exist.

If I'm not wrong translations should be kept in a sepparate messages folder.

Have a nice day!

**Comment by keltstr** [comment]
I just added a file with the required translation

**Comment by yaskypro** [comment]
I created file common/messages/ru/app.php for my locale.
