### ISSUE TITLE
Just sugestion

### ISSUE THREAD

**Issue by xiaomalover** [trntv/yii2-file-kit#59]
I think the base_url should store in config files, do not need store in  every db recorder.

**Comment by trntv** [comment]
``
'baseUrlAttribute' => false
``

**Comment by keltstr** [comment]
It may be necessary to use the setting as default?
if  'baseUrlAttribute' => false, then how to store information about the storage1 or storage2 ?

**Comment by xiaomalover** [comment]
Thx, but if I set  'baseUrlAttribute' => false, the image preview will can't work

**Comment by trntv** [comment]
set ``baseUrlAttribute`` to property that isn't in your table schema. 
```php
class SomeModel extends ActiveRecord
{
    public $virtualBaseUrl;

   public function behaviors()
   {
     return [
        'file' => [
            'class' => 'trntv\filekit\behaviors\UploadBehavior',
            'baseUrlAttribute' => 'virtualBaseUrl',
        ],
     ];
   }
}
```

**Comment by xiaomalover** [comment]
Thank you.
