### ISSUE TITLE
file-kit Image Pixelated

### ISSUE THREAD

**Issue by dbd5** [trntv/yii2-file-kit#60]
Hi Eugene,

Somehow my file upload setup seems to make my small images (mostly about 4kb) pixelated.
I'm not sure if they are processed in any way but what I would really like is that they are not resized at all or processed in any way. How can I achieve that?

Regards and thanks for your help,

Adam
_______
PRESENT CONFIG

             'avatar-upload' => [
                'class' => UploadAction::className(),
                'deleteRoute' => 'avatar-delete',
                'on afterSave' => function ($event) {
                    /* @var $file \League\Flysystem\File */
                    $file = $event->file;
                    $img = ImageManagerStatic::make($file->read())->fit(382, 215);
                    $file->put($img->encode());
                }
            ],

**Comment by trntv** [comment]
Remove 'on afterSave' from your config.

**Comment by dbd5** [comment]
Resolved, thank you Sir!

Adam
