### ISSUE TITLE
file upload using AWS

### ISSUE THREAD

**Issue by yiioverflow** [trntv/yii2-file-kit#68]
{"name":"PHP Warning","message":"fclose(): 13 is not a valid stream resource","code":2,"type":"yii\\base\\ErrorException","file":"/var/www/html/goodwin-brothers/components/filesystem/StorageEngine.php","line":101,"stack-trace":["#0 [internal function]: yii\\base\\ErrorHandler->handleError(2, 'fclose(): 13 is...', '/var/www/html/g...', 101, Array)","#1 /var/www/html/goodwin-brothers/components/filesystem/StorageEngine.php(101): fclose(Resource id #13)","#2 /var/www/html/goodwin-brothers/vendor/trntv/yii2-file-kit/src/actions/UploadAction.php(124): app\\components\\filesystem\\StorageEngine->save(Object(yii\\web\\UploadedFile))","#3 [internal function]: trntv\\filekit\\actions\\UploadAction->run()","#4 /var/www/html/goodwin-brothers/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array)","#5 /var/www/html/goodwin-brothers/vendor/yiisoft/yii2/base/Controller.php(154): yii\\base\\Action->runWithParams(Array)","#6 /var/www/html/goodwin-brothers/vendor/yiisoft/yii2/base/Module.php(454): yii\\base\\Controller->runAction('upload', Array)","#7 /var/www/html/goodwin-brothers/vendor/yiisoft/yii2/web/Application.php(84): yii\\base\\Module->runAction('file-storage/up...', Array)","#8 /var/www/html/goodwin-brothers/vendor/yiisoft/yii2/base/Application.php(375): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))","#9 /var/www/html/goodwin-brothers/web/index.php(12): yii\\base\\Application->run()","#10 {main}"]}

**Comment by yiioverflow** [comment]
Can you help me please ? File upload works well if i upload in local filesystem

**Comment by trntv** [comment]
I'll check it in a few days.

**Comment by trntv** [comment]
https://github.com/trntv/yii2-file-kit/blob/master/README.md#using-filesystem-builder
