### ISSUE TITLE
Invalid $messagesCategory in Upload Widget

### ISSUE THREAD

**Issue by NickolayCh** [trntv/yii2-file-kit#86]
It seems like:

public $messagesCategory = 'filekit/widget';

in yii2-file-kit/src/widget/Upload.php is wrong, as I'm getting these errors (changing to just 'widget' works fine):

The message file for category 'filekit/widget' does not exist: .../vendor/trntv/yii2-file-kit/src/widget/messages/ru/filekit/widget.php

**Comment by dimm-nn** [comment]
May be better to change the parameter 'fileMap' when registering posts in Upload.php:
```php    protected function registerMessages()
    {
        if (!array_key_exists($this->messagesCategory, Yii::$app->i18n->translations)) {
            Yii::$app->i18n->translations[$this->messagesCategory] = [
                'class' => 'yii\i18n\PhpMessageSource',
                'sourceLanguage' => 'en-US',
                'basePath'=> __DIR__ . '/messages',
                'fileMap'=>[
                    $this->messagesCategory => 'widget.php'
                ],
            ];
        }
    }```

**Comment by trntv** [comment]
fixed
